### ISSUE TITLE
Need help with led

### ISSUE THREAD

**Issue by 4dvn** [Bananut-Electronics/MiDispositivoMIDI_V3#6]
I have to make the 4x4 buttons matrix on arduino pro micro but need help for ws2812 can change rgb ledtrip with velocity like midi fighter spectra

**Comment by alrevuelta** [comment]
If I understood correctly, you would like to change the colour intensity of the RGB leds? If so, please have a look to [this example](https://github.com/Bananut-Electronics/MiDispositivoMIDI_V3/blob/master/examples/MDM_V3_Library_ConfigureColors/MDM_V3_Library_ConfigureColors.ino). The intensity is a value from 0 to 255, so if you set 100, it will be less brighter. First element in the array is R, second G and third B.

```c
void setup() {
  // Configure the colors when the LED is not pressed
  uint8_t offColors[3] = {255, 0, 0};
  mdm.setOffColors( offColors );

  // Configure the colors when the LED is pressed
  uint8_t onColors[3] = {0, 255, 0};
  mdm.setOnColors( onColors );
}
```

**Comment by 4dvn** [comment]
> If I understood correctly, you would like to change the colour intensity of the RGB leds? If so, please have a look to [this example](https://github.com/Bananut-Electronics/MiDispositivoMIDI_V3/blob/master/examples/MDM_V3_Library_ConfigureColors/MDM_V3_Library_ConfigureColors.ino). The intensity is a value from 0 to 255, so if you set 100, it will be less brighter. First element in the array is R, second G and third B.
> 
> ```c
> void setup() {
>   // Configure the colors when the LED is not pressed
>   uint8_t offColors[3] = {255, 0, 0};
>   mdm.setOffColors( offColors );
> 
>   // Configure the colors when the LED is pressed
>   uint8_t onColors[3] = {0, 255, 0};
>   mdm.setOnColors( onColors );
> }
> ```

Is that possible to adding more color than 3 color basic?
I just test with this library but the led not bright with button push
    https://github.com/tttapa/Control-Surface/blob/master/examples/2.%20MIDI%20Input/1.%20LEDs/10.Note-FastLED-ColorMapper/10.Note-FastLED-ColorMapper.ino

**Comment by alrevuelta** [comment]
Regarding your first question "Is that possible to adding more color than 3 color basic?" Yes, it is possible, you can do something like `{100, 25, 200}` and you will be mixing some red with a bit of green and a lot of blue.

If you load the code that I mentioned above, you should be able to see the colours that you have configured. I assume that you have a MIDI receiver open in the computer. Let me know if it doesn't work for you, but please, state your problem with providing more details.

**Comment by 4dvn** [comment]
I need the schematic before made the pcb of this example:

https://github.com/4dvn/MiDispositivoMIDI_V3/blob/master/examples/MDM_V3_NoLibrary_DefaultCode/MDM_V3_NoLibrary_DefaultCode.ino

, can you define the pinout to me of cd4067 and matrix, led, I use the diy 4x4 button matrix pad and 4x4 ws2812b, thank you!

**Comment by alrevuelta** [comment]
All the documentation can be found in this repo. For pinout refer either to the [Wiki](https://github.com/Bananut-Electronics/MiDispositivoMIDI_V3/wiki) or the pcb schematics [here](https://github.com/Bananut-Electronics/MiDispositivoMIDI_V3/tree/master/hardware)

Since your initial question was already answered, I'm closing this.
