### ISSUE TITLE
MDM_V3_NoLibrary 4x4 mod by @4dvn

### ISSUE THREAD

**Issue by 4dvn** [Bananut-Electronics/MiDispositivoMIDI_V3#7]
# Ableton drumrack mapped for first open from note 36-51 of first bank.
[MDM_V3_NoLibrary4x4.zip](https://github.com/Bananut-Electronics/MiDispositivoMIDI_V3/files/4112080/MDM_V3_NoLibrary4x4.zip)

**Comment by alrevuelta** [comment]
Is this an issue? If so, please state what is your problem

**Comment by 4dvn** [comment]
> Is this an issue? If so, please state what is your problem

I adding the correct drumrack note, can you invite me to the Project coboration?

**Comment by alrevuelta** [comment]
If this is a contribution, please read how to contribute on Github. Use a "Pull Request".

**Comment by 4dvn** [comment]
I can't add the "pull request" is showing the error, here is my email on github account: vuha.hau@hyper.vn, can you add me to the project?
![9377BE05-E04F-4BDC-9EB1-F5C1CCD1CB5E](https://user-images.githubusercontent.com/46510477/73124728-2cc45300-3fd1-11ea-83d0-2807f1249534.png)

**Comment by alrevuelta** [comment]
There is not need to add you. Read how to create a pull request.
